version: '3.9'

services:
  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: backend
    build: backend/
    ports:
      - "8080:8080"
    volumes:
      - ./evaluation_config:/app/evaluation_config
      - ./backend/inputs:/app/inputs
      - ./backend/outputs:/app/outputs